spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://127.0.0.1:3306/sky_tools?useSSL=false&useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: "root"
    #初始化链接数
    initialSize: 5
    #最小的空闲连接数
    minIdle: 5
    #最大活动连接数
    maxActive: 20
    #从池中取连接的最大等待时间，单位ms
    maxWait: 60000
    #每XXms运行一次空闲连接回收器
    timeBetweenEvictionRunsMillis: 60000
    #池中的连接空闲XX毫秒后被回收
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT1FROMDUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall,log4j
    logSlowSql: true
  resources:
    static-locations: classpath:/templates,classpath:/static
  redis:
    host: 127.0.0.1
logging:
  level:
    com.sky.mapper: trace


