spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/sky_tools?useSSL=false&useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 3302983qq
  resources:
    static-locations: classpath:/templates,classpath:/static
  redis:
    host: 127.0.0.1
logging:
  level:
    com.sky.mapper: trace
